--Part-A

--1. Write a scalar function to print "Welcome to DBMS Lab".
	CREATE OR ALTER FUNCTION FN_WELCOME_MSG()
	RETURNS VARCHAR(30)
	AS
	BEGIN
		DECLARE @MSG VARCHAR(30) 
		SET @MSG = 'WELCOME TO DBMS-II LAB' 
		RETURN @MSG
	END
	GO

	SELECT DBO.FN_WELCOME_MSG()

--2. Write a scalar function to calculate simple interest.
	CREATE OR ALTER FUNCTION FN_CAL_SI(@PRINCIPLE DECIMAL(8,2) ,@RATE DECIMAL(5,2) , @TIME DECIMAL(5,2))
	RETURNS DECIMAL(8,2)
	AS
	BEGIN
		DECLARE @SI DECIMAL(8,2)
		SET @SI = (@PRINCIPLE * @RATE * @TIME)/100
		RETURN @SI
	END
	GO

	SELECT DBO.FN_CAL_SI(200.00 ,3.00 ,4.00)

--3. Function to Get Difference in Days Between Two Given Dates
	CREATE OR ALTER FUNCTION FN_DATE_DIFF(@INITIALDATE DATE , @FINALDATE DATE)
	RETURNS INT
	AS
	BEGIN
		DECLARE @DATEDIFFERENCE INT
		SET @DATEDIFFERENCE = DATEDIFF(DAY,@INITIALDATE,@FINALDATE)
		RETURN @DATEDIFFERENCE
	END
	GO

	SELECT DBO.FN_DATE_DIFF('2006-01-01','2006-07-01')

--4. Write a scalar function which returns the sum of Credits for two given CourseIDs.
	CREATE OR ALTER FUNCTION FN_SUM_COURSE_CREDITS(@CID1 VARCHAR(10), @CID2 VARCHAR(10))
	RETURNS INT
	AS
	BEGIN
		DECLARE @SUM INT ;
		SET @SUM = (SELECT SUM(COURSECREDITS) AS TOTAL_CREDITS FROM COURSE WHERE CourseID IN (@CID1, @CID2))
		RETURN @SUM
	END
	GO

	SELECT DBO.FN_SUM_COURSE_CREDITS('IT101','CS201')

--5. Write a function to check whether the given number is ODD or EVEN.
	CREATE OR ALTER FUNCTION FN_CHECK_ODD_EVEN(@NUM INT)
	RETURNS VARCHAR(30)
	AS
	BEGIN
		DECLARE @MSG VARCHAR(30)
		IF(@NUM % 2 = 0)
			SET @MSG = 'NUMBER IS EVEN'
		ELSE
			SET @MSG = 'NUMBER IS ODD'
		RETURN @MSG
	END
	GO

	SELECT DBO.FN_CHECK_ODD_EVEN(1)

--6. Write a function to print number from 1 to N. (Using while loop)
	CREATE OR ALTER FUNCTION FN_PRINT_1TO_N(@NUM INT)
	RETURNS VARCHAR(100)
	AS
	BEGIN
		DECLARE @COUNT INT ,@OUTPUT VARCHAR(100);
		SET @COUNT=1;
		SET @OUTPUT='';
		WHILE(@COUNT<=@NUM)
		BEGIN
			SET @OUTPUT = @OUTPUT + CAST(@COUNT AS VARCHAR(10))  + ' '
			SET @COUNT =@COUNT+1
		END
		RETURN @OUTPUT
	END
	GO

	SELECT DBO.FN_PRINT_1TO_N(10)

--7. Write a scalar function to calculate factorial of total credits for a given CourseID.
	CREATE OR ALTER FUNCTION FN_CAL_FACT_COURSECREDITS(@COURSEID VARCHAR(10))
	RETURNS INT
	AS
	BEGIN
		DECLARE @FACT INT ,@COUNT INT,@COURSECREDITS INT
		SET @FACT = 1
		SET @COUNT = 1
		SET @COURSECREDITS = (SELECT COURSECREDITS FROM COURSE WHERE CourseID = @COURSEID);

		WHILE(@COUNT <= @COURSECREDITS)
		BEGIN
			SET @FACT = @FACT * @COUNT
			SET @COUNT = @COUNT+1
		END
		RETURN @FACT
	END
	GO

	SELECT DBO.FN_CAL_FACT_COURSECREDITS('CS101')

--8. Write a scalar function to check whether a given EnrollmentYear is in the past, current or future (Casestatement)
	CREATE OR ALTER FUNCTION FN_CHECK_ENROLLMENT_YEAR(@YEAR INT)
	RETURNS VARCHAR(30)
	AS
	BEGIN
		DECLARE @MSG VARCHAR(30),@CURRENTYEAR INT
		SET @CURRENTYEAR = (SELECT YEAR(GETDATE()))

		IF(@YEAR>@CURRENTYEAR)
			SET @MSG = 'ENROLLMENT YEAR WILL IN FUTURE'
		ELSE IF(@YEAR<@CURRENTYEAR)
			SET @MSG = 'ENROLLMENT YEAR WAS IN PAST'
		ELSE
			SET @MSG = 'ENROLLMENT YEAR IS IN PRESENT'
		RETURN @MSG
	END
	GO

	SELECT DBO.FN_CHECK_ENROLLMENT_YEAR(2094)

--9. Write a table-valued function that returns details of students whose names start with a given letter.
	CREATE OR ALTER FUNCTION FN_STUDETAILS(@FIRSTCHAR VARCHAR(1))
	RETURNS TABLE
	AS
	RETURN
		SELECT * FROM STUDENT 
		WHERE STUNAME LIKE @FIRSTCHAR+'%'
	
	SELECT * FROM FN_STUDETAILS('R')

--10. Write a table-valued function that returns unique department names from the STUDENT table.
	CREATE OR ALTER FUNCTION FN_UNIQUE_DEPT()
	RETURNS TABLE
	AS
	RETURN
		SELECT DISTINCT STUDEPARTMENT
		FROM STUDENT

	SELECT * FROM FN_UNIQUE_DEPT()

--Part-B
--11. Write a scalar function that calculates age in years given a DateOfBirth.
	CREATE OR ALTER FUNCTION FN_CAL_AGE(@DATEODBIRTH DATE)
	RETURNS INT
	AS
	BEGIN
		DECLARE @AGE INT ,@CURRENTDATE DATE
		SET @CURRENTDATE = (SELECT GETDATE())

		SET @AGE = DATEDIFF(YEAR,@DATEODBIRTH,@CURRENTDATE)
		RETURN @AGE
	END
	GO

	SELECT DBO.FN_CAL_AGE('2006-07-01')
	
--12. Write a scalar function to check whether given number is palindrome or not.
	CREATE OR ALTER FUNCTION FN_CHECK_NUM_PALINDROM(@NUM INT)
	RETURNS VARCHAR(30)
	AS
	BEGIN
		DECLARE @REVERSEOFNUM INT,@MSG VARCHAR(30)
		SET @NUM = CAST(@NUM AS VARCHAR(20))
		SET @REVERSEOFNUM = (SELECT REVERSE(@NUM))
		SET @REVERSEOFNUM = CAST(@REVERSEOFNUM AS INT)
		SET @NUM = CAST(@NUM AS INT)

		IF(@NUM = @REVERSEOFNUM)
			SET @MSG = 'NUMBER IS PALINDROME'
		ELSE
			SET @MSG = 'NUMBER IS NOT PALINDROME'
		RETURN @MSG
	END
	GO

	SELECT DBO.FN_CHECK_NUM_PALINDROM(121)


--13. Write a scalar function to calculate the sum of Credits for all courses in the 'CSE' department.
	CREATE OR ALTER FUNCTION FN_SUM_CREDITS(@DEPTNAME VARCHAR(5))
	RETURNS INT
	AS
	BEGIN
		DECLARE @SUM INT 
		SET @SUM = (SELECT SUM(COURSECREDITS) AS TOTAL_CREDITS FROM COURSE WHERE COURSEDEPARTMENT = @DEPTNAME )
		RETURN @SUM
	END
	GO

	SELECT DBO.FN_SUM_CREDITS ('CSE')

--14. Write a table-valued function that returns all courses taught by faculty with a specific designation.
	CREATE OR ALTER FUNCTION FN_FACULTY_DATA(@FACULTYDESIGNATION VARCHAR(20))
	RETURNS TABLE
	AS
	RETURN
	
		SELECT DISTINCT C.COURSENAME ,F.FACULTYNAME,F.FacultyDesignation
		FROM COURSE_ASSIGNMENT CA JOIN FACUILTY F
		ON CA.FacultyID = F.FacultyID
		JOIN COURSE C
		ON CA.CourseID = C.CourseID
		WHERE FacultyDesignation = @FACULTYDESIGNATION

	SELECT * FROM FN_FACULTY_DATA('Associate Prof')


--Part - C
--15. Write a scalar function that accepts StudentID and returns their total enrolled credits (sum of credits from all active enrollments).
	CREATE OR ALTER FUNCTION FN_SUM_OF_ACTIVE_COURSE_CREDITS(@STUID INT)
	RETURNS INT
	AS
	BEGIN
		DECLARE @SUM INT
		SET @SUM = (SELECT SUM(COURSECREDITS) AS TOTAL_CREDITS 
					FROM ENROLLMENT E JOIN COURSE C
					ON E.CourseID  = C.CourseID
					WHERE E.STUDENTID = @STUID )
		RETURN @SUM
	END
	GO

	SELECT DBO.FN_SUM_OF_ACTIVE_COURSE_CREDITS (1)

--16. Write a scalar function that accepts two dates (joining date range) and returns the count of faculty who joined in that period.
	CREATE OR ALTER FUNCTION FN_COUNT_FACULTY (@INITIALDATE DATE ,@FINALDATE DATE)
	RETURNS INT
	AS
	BEGIN
		DECLARE @COUNTfACULTY INT
		SET @COUNTfACULTY = (SELECT COUNT(FACULTYID) AS TOTAL_FACULTY FROM FACUILTY WHERE FacultyJoiningDate BETWEEN @INITIALDATE AND @FINALDATE)
		RETURN @COUNTfACULTY
	END
	GO

	SELECT DBO.FN_COUNT_FACULTY('2014-07-15','2020-08-20')
